export type Pregunta = {
  categoria: string
  pregunta: string
  explicacion: string
  confusion: string
  porQuePasa: string
  solucion: string
  tutorial: string[]
}

export const PREGUNTAS: Pregunta[] = [
  {
    categoria: 'Gestión',
    pregunta: '¿Dónde encuentro los productos de mis proveedores?',
    explicacion: 'Todos los productos —los tuyos y los de tus proveedores— viven juntos en la misma pantalla de Productos. Un producto de proveedor se distingue por la etiqueta "📦" con el nombre del proveedor debajo del SKU.',
    confusion: 'Se busca una sección aparte solo para "productos de proveedores" y no existe — todos están mezclados en el mismo catálogo, filtrables por proveedor.',
    porQuePasa: 'En la mayoría de las tiendas online, "productos propios" y "de terceros" se manejan por separado. Aquí se decidió mezclarlos en un solo catálogo para que el admin nunca tenga que pensar "¿esto es mío o de alguien más?" al gestionar inventario, pero eso rompe la expectativa de tener una lista aparte.',
    solucion: 'Usar siempre el filtro "📦 Proveedores" arriba de la tabla cuando se busque solo lo de un proveedor específico, en vez de intentar encontrar una pantalla separada.',
    tutorial: [
      'Clic en Productos en el menú lateral.',
      'Usa el filtro "📦 Proveedores" arriba de la tabla para ver solo los de un proveedor específico.',
      'La etiqueta "📦 Nombre del proveedor" debajo del SKU te dice de quién es cada producto.',
    ],
  },
  {
    categoria: 'Gestión',
    pregunta: '¿Dónde veo las solicitudes de productos nuevos que mandan los proveedores?',
    explicacion: 'Cuando un proveedor registra un producto nuevo, no aparece automáticamente en el catálogo — queda en una lista de solicitudes pendientes de tu aprobación, escondida detrás de un botón dentro de Productos.',
    confusion: 'El botón "Solicitudes" no es muy visible y no se abre solo — hay que saber que existe y darle clic para ver si hay algo pendiente. También puedes verlo desde el Dashboard: la tarjeta "Pendientes de aprobación" te lleva directo ahí con el panel ya abierto.',
    porQuePasa: 'El panel de solicitudes se diseñó como algo que se abre "cuando hace falta" para no ocupar espacio permanente en la pantalla de Productos, pero eso significa que su existencia depende de que el admin recuerde revisarlo.',
    solucion: 'El número junto al botón "Solicitudes" (y la tarjeta del Dashboard) es la señal a la que hay que acostumbrarse — revisar el Dashboard al iniciar el día es más confiable que recordar entrar a Productos a buscarlo manualmente.',
    tutorial: [
      'Clic en Productos en el menú lateral.',
      'Arriba a la derecha, clic en el botón "Solicitudes" (muestra un número si hay pendientes).',
      'Revisa cada solicitud y dale "Aprobar y publicar" o "Rechazar".',
      'Atajo: desde el Dashboard, la tarjeta "Pendientes de aprobación" te lleva aquí directo.',
    ],
  },
  {
    categoria: 'Gestión',
    pregunta: '¿Dónde administro a mis proveedores?',
    explicacion: 'Los proveedores no tienen su propio botón en el menú — viven dentro de Clientes, en una pestaña aparte arriba de la tabla.',
    confusion: 'Se busca un ítem "Proveedores" en el menú lateral y no existe como tal, porque comparte pantalla con Clientes.',
    porQuePasa: 'Clientes y Proveedores comparten mucha lógica en común (son "cuentas" de personas relacionadas con la tienda), así que se combinaron en una sola pantalla con pestañas para no duplicar código — pero eso oculta a los proveedores detrás de un menú que, por nombre, suena a que es solo para clientes.',
    solucion: 'Acostumbrarse a que "Clientes" en este panel significa "personas y negocios", no solo compradores — el buscador Ctrl+K no busca proveedores (solo productos, ventas y clientes), así que ir directo a Clientes → Proveedores sigue siendo el camino más confiable.',
    tutorial: [
      'Clic en Clientes en el menú lateral.',
      'Arriba de la tabla, clic en la pestaña "📦 Proveedores".',
      'Ahí puedes ver, suspender o reactivar cada proveedor.',
      'Si esperas gente que quiere registrarse como proveedor nuevo, el botón "🆕 Nuevos proveedores" está en esa misma pantalla, arriba a la izquierda.',
    ],
  },
  {
    categoria: 'Gestión',
    pregunta: '¿Cuál es la diferencia entre "Mensajes" y "Comentarios"?',
    explicacion: '"Mensajes" (en el menú principal) son consultas de clientes sobre un producto específico. "Comentarios" (dentro de Configuración) es soporte general que no está relacionado a ningún producto en particular.',
    confusion: 'Suenan casi igual y un cliente puede escribir por cualquiera de los dos caminos, así que un mensaje puede estar en cualquiera de los dos lugares según de qué haya hablado el cliente.',
    porQuePasa: 'El sistema de chat se separó en dos según el tipo de conversación (con o sin producto asociado) para que el admin no tenga que leer decenas de mensajes de soporte general buscando los que sí requieren revisar un producto — pero los nombres elegidos ("Mensajes" y "Comentarios") no comunican esa diferencia por sí solos.',
    solucion: 'Pensarlo así: si el cliente mencionó un producto, va a "Mensajes"; si fue una queja o duda general (envíos, cuenta, etc.), va a "Comentarios". Revisar ambos con la misma frecuencia hasta que se vuelva costumbre.',
    tutorial: [
      'Si el cliente preguntó sobre un producto: revísalo en Mensajes, en el menú lateral.',
      'Si el cliente escribió soporte general (no sobre un producto): está en Configuración → Comentarios.',
      'Ambos se comportan igual (puedes responder desde ahí), solo cambia dónde se guardan según el tema.',
    ],
  },
  {
    categoria: 'Gestión',
    pregunta: '¿Dónde veo las solicitudes de gente que quiere registrarse como proveedor?',
    explicacion: 'Es distinto de las solicitudes de productos — estas son de personas nuevas que quieren empezar a vender en tu tienda, y también viven dentro de Clientes → Proveedores.',
    confusion: 'Se confunde fácilmente con las solicitudes de productos nuevos (que están en Productos) — son dos listas de "pendientes" completamente separadas.',
    porQuePasa: 'Son dos procesos de aprobación distintos que nacieron en momentos distintos del desarrollo del proyecto (primero se armó la aprobación de productos, después la de registro de proveedores nuevos) y cada una se colocó junto a la pantalla más relacionada con su tema, sin unificarlas en un solo lugar de "cosas por aprobar".',
    solucion: 'Regla simple: "aprobar un producto" → Productos. "Aprobar una persona nueva" → Clientes → Proveedores. El Dashboard también avisa de ambas por separado, en tarjetas distintas.',
    tutorial: [
      'Clic en Clientes en el menú lateral.',
      'Pestaña "📦 Proveedores".',
      'Botón "🆕 Nuevos proveedores" arriba a la izquierda (muestra un número si hay solicitudes).',
      'Aprobar crea la cuenta del proveedor automáticamente y le manda su acceso por correo.',
    ],
  },
  {
    categoria: 'Ventas',
    pregunta: '¿Qué significa cada estado de un pedido?',
    explicacion: 'Un pedido pasa por: Pendiente (recién creado, sin cobro confirmado) → En proceso → Pagado (el cobro ya se confirmó, aquí se descuenta el stock) → Enviado. También puede quedar Cancelado.',
    confusion: 'Se piensa que "Pendiente" significa que algo salió mal, cuando en realidad es el estado normal de arranque de cualquier pedido nuevo hasta que se confirma el pago.',
    porQuePasa: 'La palabra "Pendiente" en el uso cotidiano suena a alerta o problema, pero aquí es simplemente el primer paso técnico del flujo — todo pedido nace así, incluso los que van a terminar pagándose sin problema segundos después.',
    solucion: 'No tratar "Pendiente" como una alarma — solo hay que actuar si un pedido se queda ahí mucho tiempo sin avanzar (eso sí puede indicar que el cliente no completó el pago).',
    tutorial: [
      'Clic en Ventas en el menú lateral.',
      'El color de cada pedido en la tabla indica su estado (amarillo=Pendiente, verde=Pagado, etc.).',
      'Puedes cambiar el estado manualmente entrando al detalle del pedido, si el pago se coordinó fuera del sistema (efectivo/transferencia).',
    ],
  },
  {
    categoria: 'Ventas',
    pregunta: '¿Por qué un pedido no cambia de estado solo?',
    explicacion: 'Solo pasa a "Pagado" automáticamente si el cliente pagó con una pasarela electrónica (Mercado Pago, PayPal, BBVA o Stripe) y esa pasarela confirmó el cobro. Si el cliente eligió Efectivo o Transferencia, el cambio de estado es manual — tú lo marcas cuando confirmes que llegó el dinero.',
    confusion: 'Se espera que todos los pedidos se actualicen solos, sin saber que "Efectivo" y "Transferencia" siempre requieren que un admin lo marque a mano.',
    porQuePasa: 'El sistema solo puede confirmar automáticamente un pago cuando existe una pasarela electrónica de por medio que le avise ("webhook"). El efectivo y la transferencia bancaria directa no tienen forma de avisarle al sistema por sí solos — nadie más que un humano puede confirmar que ese dinero realmente llegó.',
    solucion: 'Revisar periódicamente los pedidos en "Pendiente" con método Efectivo/Transferencia y marcarlos manualmente en cuanto se confirme el pago, en vez de esperar a que cambien solos.',
    tutorial: [
      'Clic en Ventas → abre el pedido en cuestión.',
      'Si el método fue Efectivo/Transferencia y ya confirmaste el pago, cambia el estado manualmente ahí mismo.',
      'Si fue con una pasarela electrónica y no cambió, revisa que esa pasarela tenga sus llaves configuradas en Configuración → Métodos de pago.',
    ],
  },
  {
    categoria: 'Tienda en línea',
    pregunta: '¿Dónde cambio lo que se ve en la página de Inicio de la tienda?',
    explicacion: 'Todo lo del Home (colores, logo, textos, fotos del carrusel, productos destacados) se edita desde Tienda en línea → Diseño, con una vista previa en vivo al lado.',
    confusion: 'Con 9 sub-secciones dentro de "Tienda en línea", cuesta adivinar cuál controla qué — "Diseño" es la más general y suele ser la que se busca primero.',
    porQuePasa: 'Cada aspecto de la tienda pública (menús, filtros, redes sociales, footer, navegación móvil...) se separó en su propia pantalla para que cada una fuera más simple individualmente, pero eso multiplica el número de lugares donde algo "podría estar".',
    solucion: 'Empezar siempre por "Diseño" para lo más visual/general, y usar la vista previa en vivo para confirmar si el cambio que buscas está ahí antes de ir a buscar en otra sub-sección.',
    tutorial: [
      'Clic en Tienda en línea en el menú lateral (te lleva directo a "Diseño").',
      'Usa la vista previa de la derecha para ver los cambios en tiempo real.',
      'Para las fotos del carrusel específicamente, ve a la sub-sección "Carrusel".',
    ],
  },
  {
    categoria: 'Tienda en línea',
    pregunta: '¿Qué es "Carrusel" y para qué sirve?',
    explicacion: 'Es donde subes las fotos grandes que rotan en la parte de arriba del Home de la tienda (con su texto encima).',
    confusion: 'Antes era la sección de "Blog" y se renombró a "Carrusel" — si ves referencias viejas a "blog" en el proyecto, es la misma sección.',
    porQuePasa: 'La función original (un blog de artículos) se descartó y se reaprovechó esa misma pantalla para el carrusel de fotos, cambiando el nombre visible pero sin renombrar internamente la dirección web (`/blog`) por no romper enlaces que ya existieran.',
    solucion: 'Guiarse siempre por el nombre que aparece en el menú ("Carrusel"), no por la URL — la URL es un detalle técnico que no necesitas conocer para usar el panel.',
    tutorial: [
      'Tienda en línea → sub-sección "Carrusel".',
      'Sube la foto, escribe el texto pequeño (kicker) y el título grande.',
      'El orden en que las agregues es el orden en que rotan en la tienda.',
    ],
  },
  {
    categoria: 'Pagos',
    pregunta: '¿Por qué un cliente dice que pagó y el pedido sigue "Pendiente"?',
    explicacion: 'Si el cliente eligió una pasarela electrónica (Mercado Pago, PayPal, BBVA o Stripe) que todavía no tiene sus llaves configuradas, el pedido se registra igual pero nunca se cobra de verdad — el cliente puede pensar que pagó sin que el cobro se haya procesado.',
    confusion: 'El switch de esa pasarela puede estar "activado" en Configuración sin tener las llaves cargadas, y nada en pantalla avisa que está encendida pero no funcional.',
    porQuePasa: 'El switch de "método de pago activo" y las credenciales de esa pasarela son dos configuraciones independientes entre sí en el sistema — activar una no valida ni depende de la otra, así que es perfectamente posible (y fácil) dejar una encendida sin llaves sin que nada lo marque como error.',
    solucion: 'Antes de activar el switch de cualquier pasarela, confirmar primero que sus 2-3 campos de credenciales ya están guardados en "🔑 Claves de pago" — activar el switch debería ser siempre el último paso, no el primero.',
    tutorial: [
      'Ve a Configuración → Métodos de pago.',
      'Revisa que la pasarela que usó el cliente tenga sus llaves realmente guardadas (no solo el switch activado).',
      'Si no las tiene, considera apagar ese método mientras no esté listo, para no confundir a más clientes.',
    ],
  },
  {
    categoria: 'Pagos',
    pregunta: '¿Dónde configuro las llaves de Mercado Pago, PayPal, BBVA o Stripe?',
    explicacion: 'Todas las credenciales de las 4 pasarelas viven en el mismo lugar, en una tarjeta que dice "🔑 Claves de pago".',
    confusion: 'El nombre de la sección ("Métodos de pago") no deja claro que ahí también se guardan credenciales sensibles — hay que entrar para descubrirlo.',
    porQuePasa: '"Métodos de pago" describe la parte que ve el cliente (qué opciones tiene para pagar); las credenciales técnicas para que esas opciones funcionen de verdad se agregaron después, en la misma pantalla, por comodidad de tenerlo todo junto — pero el nombre nunca se actualizó para reflejar que también vive ahí lo sensible.',
    solucion: 'Recordar que en esta pantalla hay dos cosas distintas apiladas: arriba, qué ve el cliente (switches); abajo, las credenciales técnicas ("🔑 Claves de pago") — conviene revisar siempre las dos partes juntas.',
    tutorial: [
      'Configuración → Métodos de pago.',
      'Activa el switch de la pasarela que quieras usar.',
      'Baja hasta la tarjeta "🔑 Claves de pago" y llena los campos de esa pasarela.',
      'Guarda — los campos secretos no vuelven a mostrar su valor una vez guardados, es normal.',
    ],
  },
  {
    categoria: 'Dashboard',
    pregunta: '¿Por qué algunas tarjetas del Dashboard se pueden clickear y otras no?',
    explicacion: 'La mayoría de las tarjetas te llevan a la pantalla relacionada con esa métrica. "Productos rechazados" y "Productos sin stock" son solo informativas — no existe todavía una pantalla dedicada a listar esos datos.',
    confusion: 'No hay ninguna señal visual que distinga cuáles se pueden tocar y cuáles no, hasta que le pasas el mouse encima.',
    porQuePasa: 'Las tarjetas se diseñaron primero todas iguales visualmente (antes ninguna era clickeable); cuando se agregó la navegación, se hizo por dato disponible y no todas las métricas tenían todavía una pantalla propia a donde llevar — el diseño visual no se actualizó para reflejar esa diferencia.',
    solucion: 'Por ahora, pasar el mouse encima es la única forma de saberlo (cambia el cursor). Sería una mejora futura agregarles alguna señal visual (una flechita, por ejemplo) a las que sí navegan.',
    tutorial: [
      'Prueba a pasar el mouse sobre una tarjeta — si el cursor cambia a "manita", es clickeable.',
      '"Pendientes de aprobación" te lleva a Productos con el panel de solicitudes ya abierto.',
      '"Proveedores registrados" te lleva a Clientes con la pestaña Proveedores ya abierta.',
    ],
  },
  {
    categoria: 'Usuarios',
    pregunta: '¿Cómo doy de alta a un empleado nuevo (vendedor, bodega, u otro admin)?',
    explicacion: 'No se puede hacer desde ningún botón del panel — hay que entrar directo a Supabase (el sistema donde vive la base de datos), crear el usuario ahí en Authentication → Users, y luego agregar su rol a mano en la tabla user_roles.',
    confusion: 'Es la única gestión de "personas" en todo el panel que no tiene una pantalla propia — todo lo demás (clientes, proveedores) sí se puede administrar sin salir del panel, así que se espera que esto también se pueda.',
    porQuePasa: 'Crear cuentas de empleados requiere permisos muy delicados (define quién puede entrar al negocio como si fuera dueño), y todavía no se construyó una pantalla propia en el panel para hacerlo de forma segura — mientras tanto, se dejó como una tarea manual directamente en Supabase, la herramienta técnica detrás del panel.',
    solucion: 'Mientras no exista esa pantalla, seguir el mensaje que ya aparece en Configuración → Usuarios y roles ("crea el usuario en Supabase, luego agrega su rol") o pedirle a quien tenga acceso técnico al proyecto que lo haga. Los roles YA creados sí se pueden cambiar o quitar desde el panel, sin volver a Supabase.',
    tutorial: [
      'Ve a Configuración → Usuarios y roles para ver el mensaje con los pasos y la lista de quién ya tiene acceso.',
      'La creación inicial del usuario requiere entrar a Supabase (Authentication → Users → Add user) — esto normalmente lo hace quien administra el proyecto técnicamente.',
      'Una vez creado en Supabase, se agrega su rol correspondiente en la tabla user_roles.',
      'A partir de ahí, cambiar su rol o quitarle el acceso ya sí se puede hacer desde esta misma pantalla del panel.',
    ],
  },
  {
    categoria: 'Usuarios',
    pregunta: '¿Dónde está el Punto de Venta?',
    explicacion: 'Existe una pantalla de Punto de Venta (para vender directo en mostrador, sin que el cliente pase por la tienda en línea), pero no aparece en el menú lateral — hay que entrar escribiendo la dirección directamente.',
    confusion: 'No hay ningún botón ni enlace visible en todo el panel que lleve ahí — es la única pantalla completa del sistema que solo se puede alcanzar sabiendo de memoria que existe.',
    porQuePasa: 'Es un descuido real: la pantalla se construyó y los permisos por rol ya la incluyen, pero se quedó sin agregar al menú lateral — no fue una decisión de diseño, simplemente se quedó pendiente.',
    solucion: 'Esta es una de las pocas cosas de esta lista que no depende de "aprender dónde está" sino que realmente falta agregarse al menú — vale la pena resolverlo agregando el enlace, no solo explicándolo.',
    tutorial: [
      'Por ahora, entra escribiendo la dirección directamente después del dominio de tu panel: /punto-de-venta',
      'Ahí puedes armar una venta directa (mostrador) igual que un pedido normal, pero sin pasar por el checkout de la tienda pública.',
      'Pídele a Claude que agregue el enlace al menú lateral si quieres tenerlo a la mano de forma permanente.',
    ],
  },
  {
    categoria: 'Envíos',
    pregunta: '¿Dónde configuro las medidas y el peso de los paquetes de un proveedor?',
    explicacion: 'Vive dentro de Envíos, en la pestaña "Paquetes por proveedor" — junto a las otras dos pestañas que son del día a día (Por enviar, Envíos activos).',
    confusion: 'Es una configuración que se hace una sola vez por proveedor (no algo que se revise a diario como las otras dos pestañas), pero está mezclada al mismo nivel que el trabajo operativo diario de envíos.',
    porQuePasa: 'Se agrupó ahí porque el dato (medidas/peso) se usa específicamente para calcular envíos, así que técnicamente pertenece al mismo tema — pero desde el punto de vista de "qué tan seguido lo uso", es un tipo de tarea distinto (configuración puntual) al de las otras dos pestañas (trabajo diario).',
    solucion: 'Configurar las medidas de cada proveedor una vez, al darlo de alta, y no esperar tener que volver seguido — a diferencia de "Por enviar"/"Envíos activos", que sí hay que revisar todos los días.',
    tutorial: [
      'Clic en Envíos en el menú lateral.',
      'Pestaña "Paquetes por proveedor".',
      'Elige el proveedor y llena las medidas/peso de sus paquetes estándar.',
      'Esto alimenta el cálculo automático de costos de envío para sus productos.',
    ],
  },
  {
    categoria: 'Ayuda del panel',
    pregunta: '¿Cómo funciona el buscador de este panel de ayuda?',
    explicacion: 'Funciona en dos pasos. Primero, mientras escribes, busca al instante entre estas mismas preguntas guardadas (por palabras en la pregunta, la explicación o la confusión común) — es gratis e inmediato, no llama a nada externo. Si ninguna coincide o ninguna resuelve tu duda, aparece un botón aparte "✨ Pregúntale a la IA" que manda tu pregunta a Gemini (la misma IA que mejora fotos de producto) junto con el contenido completo de estas preguntas, para que responda con información real de cómo funciona este panel — no información genérica de internet.',
    confusion: 'Se puede pensar que escribir ya activa la IA automáticamente, o que la IA "sabe todo" del panel por su cuenta — en realidad solo conoce lo que está escrito en estas preguntas, nada más, y nunca se activa sola.',
    porQuePasa: 'Activar la IA en cada tecleo gastaría cuota gratuita de Gemini muy rápido con preguntas a medio escribir, así que se diseñó a propósito para que la IA sea un paso extra, bajo demanda, después de que la búsqueda local ya no encontró nada útil — y como la IA no tiene acceso al código del panel, solo puede responder con lo que ya está redactado aquí.',
    solucion: 'Si la respuesta de la IA no ayuda o parece incompleta, lo más probable es que ese tema todavía no esté cubierto en ninguna de las preguntas guardadas — vale la pena pedir que se agregue una pregunta nueva sobre eso en vez de insistir con la IA.',
    tutorial: [
      'Escribe tu duda en el textbox — si alguna pregunta guardada coincide, aparece al instante en la lista.',
      'Si no aparece nada útil, dale clic a "✨ Pregúntale a la IA" debajo de los resultados.',
      'La respuesta aparece en un recuadro azul justo debajo del botón, basada solo en las preguntas ya guardadas.',
      'Si el tema es nuevo y ni la IA lo resuelve bien, es señal de que conviene agregar una pregunta nueva a esta lista.',
    ],
  },
  {
    categoria: 'Ayuda del panel',
    pregunta: '¿Qué busca (y qué no busca) el buscador global Ctrl+K?',
    explicacion: 'El buscador rápido de arriba (Ctrl+K, el ícono de lupa) busca solo en tres cosas: nombre de producto, número de venta, y nombre/email de cliente. No busca proveedores, mensajes, ni nada dentro de Tienda en línea o Configuración.',
    confusion: 'Se espera que Ctrl+K encuentre cualquier cosa del panel (como buscar en Google), incluyendo proveedores o una sección de configuración — y al no aparecer nada, se piensa que el dato no existe o que hay un error.',
    porQuePasa: 'El buscador se construyó enfocado en lo que más se busca en el día a día operativo (encontrar un producto, revisar una venta, ubicar un cliente), y nunca se amplió para cubrir proveedores ni el resto de secciones del panel.',
    solucion: 'Para proveedores, ir directo a Clientes → Proveedores. Para ajustes de Tienda en línea o Configuración, usar el menú lateral — Ctrl+K por ahora es solo para datos operativos (producto/venta/cliente), no para navegar el panel.',
    tutorial: [
      'Ctrl+K (o el ícono de lupa arriba) abre el buscador rápido.',
      'Escribe el nombre de un producto, el número de una venta, o el nombre/email de un cliente.',
      'Para todo lo demás (proveedores, configuración, tienda en línea), usa el menú lateral en vez del buscador.',
    ],
  },
  {
    categoria: 'Configuración',
    pregunta: '¿Por qué hay dos lugares para el teléfono/dirección de contacto?',
    explicacion: 'El teléfono y dirección que se guardan en Configuración → Contacto, y el teléfono/dirección que se guardan en Tienda en línea → Footer → "Contacto y redes", son campos DISTINTOS — y el footer público de la tienda los muestra a los dos al mismo tiempo, como dos líneas separadas.',
    confusion: 'Se llena solo uno de los dos (el que se encuentra primero) y no se entiende por qué el footer de la tienda se ve con un solo teléfono, o por qué de repente aparecen dos teléfonos distintos en el footer si se llenan ambos por separado.',
    porQuePasa: 'Son dos formularios que se construyeron en momentos distintos del proyecto: "Contacto" es información general del negocio, y el campo del Footer se agregó después específicamente para lo que se ve al fondo de la tienda pública — nunca se unificaron en un solo lugar, así que ahora conviven dos campos con un propósito parecido pero técnicamente independientes.',
    solucion: 'Decidir un solo teléfono/dirección "oficial" y llenarlo en los dos lugares por consistencia, o dejar el de Footer vacío si solo quieres que se muestre el de Contacto — revisar el footer de la tienda pública después de guardar para confirmar cómo se ve.',
    tutorial: [
      'Configuración → Contacto: teléfono, WhatsApp y dirección "generales" del negocio.',
      'Tienda en línea → Footer → "Contacto y redes": un teléfono y dirección aparte, específicos para el pie de página público.',
      'El footer de la tienda muestra AMBOS si los dos están llenos — revisa cómo se ve entrando a la tienda pública después de guardar.',
    ],
  },
  {
    categoria: 'Gestión',
    pregunta: '¿Por qué la etiqueta de un cliente (VIP/Regular/Nuevo) vuelve a cambiar sola después de editarla?',
    explicacion: 'La etiqueta se puede cambiar a mano desde el formulario de editar cliente, pero también se recalcula automáticamente cada vez que se registra una venta pagada de ese cliente: 8 o más compras pagadas = VIP, 3 a 7 = Regular, menos de 3 = Nuevo. Un cambio manual puede "perderse" en cuanto el cliente hace una compra nueva.',
    confusion: 'Se edita la etiqueta a mano (por ejemplo, subir a alguien a VIP como cortesía) y más adelante aparece de nuevo como "Regular" o "Nuevo", sin que quede claro por qué "se revirtió sola".',
    porQuePasa: 'El campo se diseñó para reflejar automáticamente el historial real de compras del cliente (así el equipo de ventas no tiene que actualizarlo a mano constantemente), pero el formulario de edición también permite tocarlo manualmente — sin ninguna advertencia de que la próxima compra pagada lo va a recalcular y pisar ese cambio.',
    solucion: 'Tratar la edición manual de la etiqueta como algo temporal/cosmético, no permanente — si quieres que un cliente se quede en VIP de forma segura, la única forma confiable es que efectivamente acumule 8+ compras pagadas, no editarlo a mano.',
    tutorial: [
      'Clic en Clientes → editar el cliente en cuestión para ver o cambiar su etiqueta manualmente.',
      'Ten en cuenta que la próxima venta marcada como "Pagado" de ese cliente puede recalcular la etiqueta sola (8+=VIP, 3-7=Regular, menos=Nuevo).',
      'Si necesitas que se quede fija sin importar sus compras, es algo que habría que resolver a nivel de código (avísale a Claude si lo necesitas).',
    ],
  },
  {
    categoria: 'Configuración',
    pregunta: '¿Para qué sirven los switches de Configuración → Notificaciones?',
    explicacion: 'Hoy por hoy, apagar o prender estos 3 switches ("Alerta de stock bajo", "Nueva venta", "Resumen diario por email") no cambia nada en la práctica: la campana de notificaciones arriba a la derecha siempre avisa de stock bajo y ventas nuevas sin importar cómo estén estos switches, y el "Resumen diario por email" no tiene ningún envío de correo conectado todavía — ninguno de los tres está realmente wireado a su switch.',
    confusion: 'Se apaga alguno pensando que va a dejar de recibir esa alerta (por ejemplo, "Nueva venta"), y la notificación sigue apareciendo igual en la campana — parece que el panel tiene un bug, cuando en realidad el switch simplemente no está conectado a nada todavía.',
    porQuePasa: 'Esta pantalla se construyó pensando en preferencias de notificación reales, pero la campana de notificaciones (arriba a la derecha) se implementó por separado y nunca se conectó a leer esta configuración — y el resumen diario por correo nunca se llegó a construir del lado del servidor (necesitaría una tarea programada que mande el email).',
    solucion: 'Por ahora, asumir que la campana siempre va a avisar de stock bajo y ventas nuevas, sin importar estos switches — no confiar en ellos para "silenciar" una alerta. Si de verdad se necesita esa función, hay que pedir que se conecte de verdad (la campana debería filtrar por estos valores, y el resumen diario necesitaría una tarea programada nueva).',
    tutorial: [
      'No hay ningún paso que "hacerlos funcionar" todavía — es una función pendiente de conectar, no un error de uso.',
      'Si quieres dejar de ver cierto tipo de alerta en la campana, por ahora la única opción es ignorarla ahí mismo.',
      'Si esta función es importante para tu operación, pídele a Claude que la conecte de verdad.',
    ],
  },
]
